[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "adenotoken/=lib/adeno/src/"
]
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config